name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees:
  - childfish
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report.
        
        **Before you do so**, try verifying your game files with Steam. There are many issues that can be put down to the game not patching correctly and using the "Verify integrtiy of game files" option in Steam is a good first thing to try.
        
        If you do not provide details on what you've tried / debugging steps. Your game version / mod version, and how to recreate the bug, then the report will be ignored.
        
        If you do not provide a title for your bug report, it will be closed.
        
        If you duplicate a post, it will be ignored.
  - type: input
    id: contact
    attributes:
      label: Discord Username
      description: If you wish, provide us your Discord Username to contact you if we need more info.
      placeholder: childfish
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the issue in detail
      description: Also tell us, what did you expect to happen?
      placeholder: "Greetings! I have an issue when I try to join to my friend. It's says 'You are joinig another player...' and that's all. I did tests with my friend and found out that this problem occurs when the host in his session kills any boss. After the murder, it's impossible to go to him, unless you rehost. Internet quality doesn't affect this any way, we tried our best to fix it". The version of the mod is 1.5.1 "
    validations:
      required: true
  - type: textarea
    id: steps-recreate
    attributes:
      label: Steps to recreate the bug
      description: Note areas, number of people, enemies and prior events if applicable
      placeholder: "Start a session, kill a random boss. Ask your friends to try to join and they will have an endless message "You are joinig to another player..." "
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of the mod are you running?
      options:
        - Select version
        - 1.5.1 (Latest)
        - 1.5.0
        - 1.4.5
        - 1.4.4 (Don't use)
        - 1.4.3
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant Crash log
      description: Please copy and paste any relevant log output. (Event viewer information about crashes could be helpful)
      placeholder: |
        1. Press Win+R
        2. Type "eventvwr", and run.
        3. Go to "Windows Logs".
        4. Go to "Application".
        5. Crashes are errors, and are sorted from latest to oldest. Select the most appropriate one.
        6. Verify that this is at the beginning: "Faulting application name: eldenring.exe"
        7. Paste the log here.
      render: shell
